os: osx
osx_image: xcode13.1
language: swift
sudo: required
git:
  quiet: true
env:
  global:
    - PROJECT="DashLine.xcodeproj"
    - SCHEME="DashLine"
    - IOS_SDK="iphonesimulator"
    - MACOS_SDK="macosx11.6"
    - TVOS_SDK="appletvsimulator9.0"
    - WATCHOS_SDK="watchsimulator3.0"
    - FRAMEWORK="RxKeyboard"
  matrix:
    - SDK="$IOS_SDK"      TEST=0  SWIFT_VERSION=5.5.1 DESTINATION="platform=iOS Simulator,name=iPhone 12"

#install:
# - swift --version
# - bundle install

before_script:
  - set -o pipefail
  - git lfs pull
  #- swift package generate-xcodeproj

before_install:
  - brew install swiftlint
  - brew install cocoapods
# - brew install git-lfs

script:
  - swiftlint
  - if [ $TEST == 1 ]; then
      xcodebuild clean SWIFT_VERSION=${SWIFT_VERSION} build test
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        -enableCodeCoverage YES
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    else
      xcodebuild clean SWIFT_VERSION=${SWIFT_VERSION} build
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi
  - bundle exec pod repo update
  - bundle exec pod lib lint --swift-version=${SWIFT_VERSION} --verbose --allow-warnings --fail-fast
before_deploy:
  - ./carthage.sh bootstrap
  - carthage build --no-skip-current --verbose | xcpretty -c
  - carthage archive DashLine
  
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: $FRAMEWORK.framework.zip
  skip_cleanup: true
  on:
    repo: ShenYj/DashLine
    tags: true
    condition: $SDK = $IOS_SDK
    